### ISSUE TITLE
Unix socket support

### ISSUE THREAD

**Issue by KalilDev** [yilmaz08/turl#3]
On instances where we want to connect to plain TCP streams, we may also want to connect to Unix domain streams. I could add this functionality. Using tcp://host:port for tcp and unix:path for unix seems sensible

**Comment by yilmaz08** [comment]
It would be awesome! If you had implemented this, I would merge it

**Comment by yilmaz08** [comment]
I am closing the issue since you haven't responded for a while. However, you can still add this feature with a PR
